import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateReportPDF({
  reportType,
  fromDate,
  toDate,
  business,
  currentUser,
  summaryData,
  tableData,
}) {
  const doc = new jsPDF();
  const primaryColor = [6, 78, 59]; // Emerald 900 (#064e3b)
  const textColor = [30, 41, 59]; // Slate 800

  // 1. Header (Store Name & Contact Info)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...primaryColor);
  doc.text(business?.name || "Barakah POS", 14, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const storeSub = [
    business?.address,
    business?.phone ? `Phone: ${business.phone}` : null,
    business?.email ? `Email: ${business.email}` : null,
  ]
    .filter(Boolean)
    .join(" | ");
  doc.text(storeSub || "POS Store Report", 14, 24);

  // Top Divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 28, 196, 28);

  // 2. Report Header Block
  const reportTitles = {
    Sales: "SALES REPORT",
    Product: "PRODUCT SALES REPORT",
    Expenses: "EXPENSE REPORT",
    GRN: "GOODS RECEIVED NOTE (GRN) REPORT",
    "Profit & Loss": "PROFIT & LOSS SUMMARY",
  };
  const reportTitle = reportTitles[reportType] || "BUSINESS REPORT";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...textColor);
  doc.text(reportTitle, 14, 37);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Period: ${fromDate} to ${toDate}`, 14, 43);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 130, 37);
  doc.text(`Generated By: ${currentUser?.name || "Admin User"}`, 130, 43);

  let currentY = 50;

  // 3. Executive Summary Cards
  if (summaryData && summaryData.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...textColor);
    doc.text("Executive Summary", 14, currentY);
    currentY += 4;

    const cardWidth = 42;
    const cardHeight = 16;
    const cardsPerRow = 4;
    summaryData.forEach((item, index) => {
      const row = Math.floor(index / cardsPerRow);
      const col = index % cardsPerRow;
      const x = 14 + col * 45;
      const y = currentY + row * 19;

      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(x, y, cardWidth, cardHeight, 2, 2, "FD");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text(item.label, x + 3, y + 5);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(...textColor);
      doc.text(String(item.value), x + 3, y + 12);
    });

    const rowsCount = Math.ceil(summaryData.length / cardsPerRow);
    currentY += rowsCount * 19 + 6;
  }

  // 4. Detailed Data Table (autoTable)
  if (tableData && tableData.headers && tableData.rows) {
    autoTable(doc, {
      startY: currentY,
      head: [tableData.headers],
      body: tableData.rows,
      theme: "striped",
      headStyles: {
        fillColor: primaryColor,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 8.5,
        textColor: [51, 65, 85],
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      margin: { top: 10, right: 14, bottom: 14, left: 14 },
      didDrawPage: (data) => {
        const str = `Page ${doc.internal.getNumberOfPages()}`;
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(str, 196, 287, { align: "right" });
        doc.text("Barakah POS — Confidential Business Report", 14, 287);
      },
    });
  }

  // 5. Download File
  const sanitizedTitle = reportType.replace(/\s+/g, "");
  const fileName = `BarakahPOS_${sanitizedTitle}Report_${fromDate}_to_${toDate}.pdf`;
  doc.save(fileName);
}
